### ISSUE TITLE
Add example using OpenHMD with Qt/QML

### ISSUE THREAD

**Issue by tripzero** [OpenHMD/OpenHMD#106]
In theory, using Scene3D, it should be really simple for someone who knows what they are doing to create an example of using OpenHMD with Qt/QML.

https://doc.qt.io/qt-5/qt3d-scene3d-example.html

**Comment by CandyAngel** [comment]
If you are interested in using OpenHMD in Qt/QML, we're happy to help you achieve such an implementation/demo. We're mostly on IRC, #openhmd@freenode. There isn't anyone who uses Qt/QML there that I know of, but we'll help regardless :)

Hope to see you there!

**Comment by TheOnlyJoey** [comment]
Any update or link to a repository so we can share this with people?

**Comment by tripzero** [comment]
I've got the repo ready to push.  Just need to finish a few things.  I will
try to prioritize it this next week.

**Comment by TheOnlyJoey** [comment]
Ah great to hear, let us know when everything is online!

**Comment by tripzero** [comment]
pushed it here: https://github.com/tripzero/qmlhmddevice

**Comment by TheOnlyJoey** [comment]
Great! will add to the website.
