### ISSUE TITLE
OpenGL support on mac

### ISSUE THREAD

**Issue by filipinascimento** [OpenHMD/OpenHMD#137]
Hello,

This is just a minor thing but the openGL examples do not compile in macOS. OpenGL tests being used to compile the opengl example do not work on macOS without some editing. That is because, on mac, OpenGL lib is linked differently from Linux and Windows, as it uses the OpenGL framework. So instead of using `-lgl` and `#include<GL/gl.h>`, you need to use `-framework OpenGL` and `#include <OpenGL/gl.h>`. The framework command seems to be needed both for compiling and linking.
Usually this piece of code is used:

```c
#ifndef MACOS
#include <GL/gl.h>
#else
#include <OpenGL/gl.h>
#endif
```

After changing this in headers and makefiles, everything seems to work fine.

**Comment by pH5** [comment]
This should be fixed now. With #145 the OpenGL example is built on Travis CI for Linux and Mac.
