### ISSUE TITLE
OpenVR model change

### ISSUE THREAD

**Issue by Ritchielambda** [OpenHMD/OpenHMD#141]
I use the model in the rendermodels\vr_controller_01_mrhat    to replace the body .obj in the rendermodels\vr_controller_vive_1_5  ,meanwhile I also change name of new model to body.obj。
but it can't work.the result is the body model can't show on screen.  I wonder if there is anything wrong

**Comment by TheOnlyJoey** [comment]
Hello,

I think you are mistaken, this is the OpenHMD repository, not the OpenVR one, different project.
