### ISSUE TITLE
Is the Oculus rift (consumer version) supported?

### ISSUE THREAD

**Issue by Brainiarc7** [OpenHMD/OpenHMD#157]
Hello,

I need some clarification on https://github.com/OpenHMD/OpenHMD/wiki/Support-List.

It's stated that the CV1 is supported. Does this also cover for the consumer version of the Rift?

**Comment by TheOnlyJoey** [comment]
Hello,

Indeed, CV1 stands for Consumer Version 1 which is the current available rift.

**Comment by Brainiarc7** [comment]
Forgive my ineptitude, its' the same device: https://en.wikipedia.org/wiki/File:Oculus-Rift-CV1-Headset-Back.jpg
