### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by CCF100** [OpenHMD/OpenHMD#158]
caleb@Caleb_Gaming_Rig /C/Users/caleb/Downloads/OpenHMD
$ make
make  all-recursive
make[1]: Entering directory `/C/Users/caleb/Downloads/OpenHMD'
Making all in src
make[2]: Entering directory `/C/Users/caleb/Downloads/OpenHMD/src'
  CCLD     libopenhmd.la
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `destroy_driver':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:469: undefined reference to `hid_exit'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `close_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:219: undefined reference to `hid_close'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `update_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:168: undefined reference to `hid_read'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `send_feature_report':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:75: undefined reference to `hid_send_feature_report'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:435: undefined reference to `hid_enumerate'
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:462: undefined reference to `hid_free_enumeration'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `get_feature_report':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:70: undefined reference to `hid_get_feature_report'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `open_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:236: undefined reference to `hid_open_path'
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:247: undefined reference to `hid_set_nonblocking'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `send_feature_report':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:75: undefined reference to `hid_send_feature_report'
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:75: undefined reference to `hid_send_feature_report'
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:75: undefined reference to `hid_send_feature_report'
drv_oculus_rift/.libs/libopenhmd_la-rift.o: In function `open_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:288: undefined reference to `hid_write'
c:\Users\caleb\Downloads\OpenHMD\src/drv_oculus_rift/rift.c:292: undefined reference to `hid_write'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `close_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:204: undefined reference to `hid_send_feature_report'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:207: undefined reference to `hid_send_feature_report'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:210: undefined reference to `hid_close'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:211: undefined reference to `hid_close'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:458: undefined reference to `hid_enumerate'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `open_device_idx':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:259: undefined reference to `hid_enumerate'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:270: undefined reference to `hid_open_path'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:284: undefined reference to `hid_free_enumeration'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `update_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:126: undefined reference to `hid_read'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `vive_read_config':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:296: undefined reference to `hid_get_feature_report'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:308: undefined reference to `hid_get_feature_report'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `vive_get_range_packet':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:331: undefined reference to `hid_get_feature_report'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:336: undefined reference to `hid_get_feature_report'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `open_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:387: undefined reference to `hid_set_nonblocking'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:398: undefined reference to `hid_set_nonblocking'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:403: undefined reference to `hid_get_manufacturer_string'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:404: undefined reference to `hid_get_product_string'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:405: undefined reference to `hid_get_serial_number_string'
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:408: undefined reference to `hid_send_feature_report'
drv_htc_vive/.libs/libopenhmd_la-vive.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_htc_vive/vive.c:481: undefined reference to `hid_free_enumeration'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `destroy_driver':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:305: undefined reference to `hid_exit'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `close_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:189: undefined reference to `hid_close'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `update_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:138: undefined reference to `hid_read'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `send_feature_report':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:55: undefined reference to `hid_send_feature_report'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:275: undefined reference to `hid_enumerate'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `open_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:202: undefined reference to `hid_open_path'
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:212: undefined reference to `hid_set_nonblocking'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `send_feature_report':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:55: undefined reference to `hid_send_feature_report'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `get_feature_report':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:50: undefined reference to `hid_get_feature_report'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `send_feature_report':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:55: undefined reference to `hid_send_feature_report'
drv_deepoon/.libs/libopenhmd_la-deepoon.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_deepoon/deepoon.c:299: undefined reference to `hid_free_enumeration'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `close_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:164: undefined reference to `hid_close'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:370: undefined reference to `hid_enumerate'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `update_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:110: undefined reference to `hid_read'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `config_command_sync':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:206: undefined reference to `hid_write'
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:208: undefined reference to `hid_read'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `open_device_idx':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:171: undefined reference to `hid_enumerate'
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:182: undefined reference to `hid_open_path'
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:196: undefined reference to `hid_free_enumeration'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `open_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:315: undefined reference to `hid_set_nonblocking'
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:321: undefined reference to `hid_write'
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:315: undefined reference to `hid_set_nonblocking'
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:321: undefined reference to `hid_write'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `open_device_idx':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:196: undefined reference to `hid_free_enumeration'
drv_wmr/.libs/libopenhmd_la-wmr.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_wmr/wmr.c:394: undefined reference to `hid_free_enumeration'
drv_psvr/.libs/libopenhmd_la-psvr.o: In function `close_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:143: undefined reference to `hid_close'
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:144: undefined reference to `hid_close'
drv_psvr/.libs/libopenhmd_la-psvr.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:255: undefined reference to `hid_enumerate'
drv_psvr/.libs/libopenhmd_la-psvr.o: In function `update_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:83: undefined reference to `hid_read'
drv_psvr/.libs/libopenhmd_la-psvr.o: In function `open_device_idx':
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:151: undefined reference to `hid_enumerate'
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:173: undefined reference to `hid_free_enumeration'
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:162: undefined reference to `hid_open_path'
drv_psvr/.libs/libopenhmd_la-psvr.o: In function `open_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:195: undefined reference to `hid_set_nonblocking'
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:206: undefined reference to `hid_set_nonblocking'
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:212: undefined reference to `hid_write'
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:215: undefined reference to `hid_write'
drv_psvr/.libs/libopenhmd_la-psvr.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:294: undefined reference to `hid_free_enumeration'
c:\Users\caleb\Downloads\OpenHMD\src/drv_psvr/psvr.c:294: undefined reference to `hid_free_enumeration'
drv_nolo/.libs/libopenhmd_la-nolo.o: In function `destroy_driver':
c:\Users\caleb\Downloads\OpenHMD\src/drv_nolo/nolo.c:347: undefined reference to `hid_exit'
drv_nolo/.libs/libopenhmd_la-nolo.o: In function `close_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_nolo/nolo.c:140: undefined reference to `hid_close'
drv_nolo/.libs/libopenhmd_la-nolo.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_nolo/nolo.c:278: undefined reference to `hid_enumerate'
drv_nolo/.libs/libopenhmd_la-nolo.o: In function `update_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_nolo/nolo.c:60: undefined reference to `hid_read'
drv_nolo/.libs/libopenhmd_la-nolo.o: In function `open_device':
c:\Users\caleb\Downloads\OpenHMD\src/drv_nolo/nolo.c:177: undefined reference to `hid_open_path'
c:\Users\caleb\Downloads\OpenHMD\src/drv_nolo/nolo.c:187: undefined reference to `hid_set_nonblocking'
drv_nolo/.libs/libopenhmd_la-nolo.o: In function `get_device_list':
c:\Users\caleb\Downloads\OpenHMD\src/drv_nolo/nolo.c:341: undefined reference to `hid_free_enumeration'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [libopenhmd.la] Error 1
make[2]: Leaving directory `/C/Users/caleb/Downloads/OpenHMD/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/C/Users/caleb/Downloads/OpenHMD'
make: *** [all] Error 2

**Comment by TheOnlyJoey** [comment]
It seems you don't have hidapi installed, or at least are not linking to hidapi.
Might be good to keep an closer eye on the documentation https://github.com/OpenHMD/OpenHMD#requirements

**Comment by CCF100** [comment]
(Forgot to mention)
I do have hidapi linked, however, when I finally managed to successfully link it, it linked 4 copies of it, and I couldn't figure out how to unlink the extra ones.

**Comment by CCF100** [comment]
I cleaned out MinGW, and reinstalled it, and now I get something completely different:
caleb@Caleb_Gaming_Rig /C/Users/caleb/Downloads/OpenHMD
$ make
make  all-recursive
make[1]: Entering directory `/C/Users/caleb/Downloads/OpenHMD'
Making all in src
make[2]: Entering directory `/C/Users/caleb/Downloads/OpenHMD/src'
  CC       libopenhmd_la-openhmd.lo
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
  CC       libopenhmd_la-platform-win32.lo
platform-win32.c: In function 'ohmd_toggle_ovr_service':
platform-win32.c:162:40: warning: passing argument 2 of 'StartServiceA' makes integer from pointer without a cast [-Wint-conversion]
   BOOL b = StartService(serviceHandle, NULL, NULL);
                                        ^~~~
In file included from c:\mingw\include\windows.h:53:0,
                 from platform-win32.c:15:
c:\mingw\include\winsvc.h:239:23: note: expected 'DWORD {aka long unsigned int}' but argument is of type 'void *'
 WINADVAPI BOOL WINAPI StartServiceA(SC_HANDLE,DWORD,LPCSTR*);
                       ^~~~~~~~~~~~~
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
  CC       drv_dummy/libopenhmd_la-dummy.lo
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
  CC       libopenhmd_la-omath.lo
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
  CC       libopenhmd_la-platform-posix.lo
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
  CC       libopenhmd_la-fusion.lo
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
  CC       libopenhmd_la-shaders.lo
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
gcc.exe: warning: C:/MinGW/msys/1.0/lib: linker input file unused because linking not done
  CC       drv_oculus_rift/libopenhmd_la-rift.lo
drv_oculus_rift/rift.c:11:20: fatal error: hidapi.h: No such file or directory
 #include <hidapi.h>
                    ^
compilation terminated.
make[2]: *** [drv_oculus_rift/libopenhmd_la-rift.lo] Error 1
make[2]: Leaving directory `/C/Users/caleb/Downloads/OpenHMD/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/C/Users/caleb/Downloads/OpenHMD'
make: *** [all] Error 2
