### ISSUE TITLE
configure does not find hidapi-libusb although installed

### ISSUE THREAD

**Issue by LordOfDragons** [OpenHMD/OpenHMD#175]
Gentoo System. The package dev-libs/libusb-1.0.21 is installed. Nevertheless the configure script complains hidapi-libusb is not installed. Either the configure check does not support version check properly or the required package is not "libusb". Can not check since the README does not contain requirements (could be libusb is not enough?)

**Comment by TheOnlyJoey** [comment]
libusb is a dependency of hidapi, which is what we used.
https://github.com/OpenHMD/OpenHMD#requirements

hidapi both has a libusb and a hidraw backend. Installing libhidapi should solve the issue.
