### ISSUE TITLE
 Detect which display port the Rift is connected to and render on it automatically

### ISSUE THREAD

**Issue by Fredz66** [OpenHMD/OpenHMD#18]
Could be useful when not in clone mode. Like the -xineramascreen <0-...> command in MPlayer, which is quite useful to display Rift-ready videos on the correct output.

Somewhat equivalent to the -adapter <n> command switch of the Unity engine but automatic instead.

**Comment by alexandre-janniaux** [comment]
Hi, is it planned to give the platform specific adapter name?

**Comment by TheOnlyJoey** [comment]
OpenHMD will not provide any rendering or direct output things by itself.
We might use something like a OpenHMD-GFX library to provide some setups, or implement some in our openglexample, but we will probably not provide this through OpenHMD as this should be handled by the compositor, not by the driver.

**Comment by alexandre-janniaux** [comment]
I'm not talking about providing rendering capabilities but instead providing the platform specific name like HDMI-A-0 so as to pair openHMD with XRandR or Wayland code for example.

**Comment by TheOnlyJoey** [comment]
This is highly different per system, so that is not something we could do.
The current way to force randr or DRM/KMS is to use the edid information to get the device, which is something xrandr does itself.

**Comment by alexandre-janniaux** [comment]
Ok, seems fair, thank you for the information !
