### ISSUE TITLE
OpenXR support?

### ISSUE THREAD

**Issue by Holzhaus** [OpenHMD/OpenHMD#209]
Khronos just released the OpenXR 0.90 spec:
https://www.khronos.org/news/press/khronos-releases-openxr-0.90-provisional-specification-for-high-performance-access-ar-vr-platforms-and-devices

Are there any plans to support this?

**Comment by TheOnlyJoey** [comment]
OpenHMD is actually part of Monado, a full open source OpenXR runtime and can already be used with OpenXR applications!
https://monado.freedesktop.org/

**Comment by Holzhaus** [comment]
Awesome!
