### ISSUE TITLE
Running OpenHMD examples corrupt the scale of other monitors

### ISSUE THREAD

**Issue by adnanmunawar** [OpenHMD/OpenHMD#212]
System
Ubuntu **18.04**
Hardware: **Nvidia GTX-1060**
Driver: **nvidia-390**
Kernel: **4.15.0.46-generic**
Device: **Occulus Rift Commercial Version**

Note: Using **Unity** Desktop rather than the default **Gnome**

The library was working fine a few months back but atm launching it messes the scaling on all the other monitors by making the scale too high and thus enlarging everything making the desktop un-useable.

**Comment by adnanmunawar** [comment]
The issue seems to stem from using Unity rather than the default Gnome. Switched back to gnome and the issue seems to have subsided

**Comment by TheOnlyJoey** [comment]
Not really a openhmd issue indeed, seems like it is WM related.
