### ISSUE TITLE
Rotation Drifting with DK2

### ISSUE THREAD

**Issue by shinyquagsire23** [OpenHMD/OpenHMD#25]
So I've been testing out my DK2 I got recently, and one application I was looking to port to the DK2 was xLava's Jedi Academy VR port. However, after correcting all the resolution values and getting everything going, I started to notice that my camera has a constant "spin" to it, and it was especially noticable in cutscenes. Just to make sure it wasn't the fault of xLava, I went into the 'simple' demo bundled in OpenHMD, and lo and behold it had a constant spin there as well when I set my HMD down.

The rotation values still change when I look around, so it's definitely not an issue of retrieving them. But regardless, something is causing this spin to occur on DK2 devices. Is it some sort of correctional measure for the DK1 which was never removed for DK2 devices, or is it the DK2 itself outputting these values?

I should also add that I tested this with the 0.4.3 SDK and the Tuscany demo, and no drifting was present.

**Comment by CandyAngel** [comment]
Was this fixed with dfc53af16323810d7c3acc9ffbb78b9fab5279d7?

**Comment by TheOnlyJoey** [comment]
Yes, this fixed the issue!
