### ISSUE TITLE
meson: add an option to disable unittests

### ISSUE THREAD

**Issue by alexandre-janniaux** [OpenHMD/OpenHMD#259]
Hi,

We're building OpenHMD as static library and don't use the unit tests. In particular, this unit test is sometime raising linking issue.

Would it be possible to add an option to disable building it ?

**Comment by TheOnlyJoey** [comment]
@pH5 any time to check on this?

**Comment by alexandre-janniaux** [comment]
Hi, if needed I can provide the correct patch for it.

**Comment by pH5** [comment]
Sure, we can add an option to disable building the tests. It would be better to investigate the linking issue though. Can you provide a build log of the failed build?
