### ISSUE TITLE
hidapi and cmake in windows

### ISSUE THREAD

**Issue by fa1ke5** [OpenHMD/OpenHMD#267]
Hi all!
I'm try to prepearing source code for MS VS project and get error after cmake . -G "Visual Studio 11 2012 Win64" command:

D:\_VR\OpenHMD\OpenHMD-master>cmake . -G "Visual Studio 11 2012 Win64"
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandle
StandardArgs.cmake:146 (message):
  Could NOT find HIDAPI (missing: HIDAPI_LIBRARY HIDAPI_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.
cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindHIDAPI.cmake:35 (find_package_handle_standard_args)
  CMakeLists.txt:49 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/_VR/OpenHMD/OpenHMD-master/CMakeFiles/CMakeOutput.log".

D:\_VR\OpenHMD\OpenHMD-master>

what a'm doing wrong?
Have you are some instriction for adding hidapi sources in OpenHMD project in windows?

**Comment by TheOnlyJoey** [comment]
This is quite a basic cmake question, you first need to build hidapi, or download the hidapi dll and make sure cmake can find it. It is the same as with every other dependency using cmake. Good luck!
