### ISSUE TITLE
No display on WMR headset/steamVR not detecting (on windows 10)

### ISSUE THREAD

**Issue by herosilas12** [OpenHMD/OpenHMD#292]
I downloaded OpenHMD-0.3.0-msvc2017.zip
and ran the .exe in that folder and it did detect the headset but there was no display and then I tried to start up steamVR but it did nothing
I want to contribute to the project but I dont have any experence coding so I can send diagnostic/tracking info if you can assist me
thank you :)
samsung odyssey+

**Comment by herosilas12** [comment]
now detects the headset but I get this error
![image](https://user-images.githubusercontent.com/36961653/82473837-c5567580-9a8f-11ea-8d1d-63c6716d6656.png)

**Comment by herosilas12** [comment]
uninstalled windows mixed reality portal and now it detects it without the error. however I still get "failed to stop OVRService, try running as admin" even though I don't have the oculus software installed or running

**Comment by TheOnlyJoey** [comment]
I think you might be confused, OpenHMD itself does not do anything when not used in a application. It seems you are trying to get the WMR running with OpenHMD for SteamVR?
https://github.com/ChristophHaag/SteamVR-OpenHMD Is the project you need then, keep in mind though that it currently requires basic software compilation knowledge, and Windows support is undergoing some patches.
