### ISSUE TITLE
Support Hypereal Pano ?

### ISSUE THREAD

**Issue by Xanadu-Zen** [OpenHMD/OpenHMD#296]
Hypereal Pano is a multi camera IR blob tracking based VR headset, this headset start selling from June 2017, Include dual or triple camera, sens controller and the HMD. dual camera  provide 240° and triple camera provide 360° tracking.
The manufacturer also released compatible tools on Windows to work with SteamVR at that time. but after January 2018, the manufacturer was transformation to other industry and no longer to support this headset.
With tons of updates from SteamVR, the compatible tools are not work with the latest SteamVR(can not detect the key press event in game ).
Now this VR headset can only work perfectly with old version SteamVR (such as macos_beta, 1.3.23).
Does anyone interested to support this devices? For necessary, I can giving a triple-Camera headset with the latest client drivers from manufacturer and old version SteamVR macos_beta for reverse engineering.

**Comment by Xanadu-Zen** [comment]
The device looks like this
![HVRpoweroff](https://user-images.githubusercontent.com/20035192/83250307-81bfe200-a1da-11ea-8df0-23a76383270a.jpg)
and it's poweron
![HVRpoweron](https://user-images.githubusercontent.com/20035192/83250373-9603df00-a1da-11ea-9db9-fe2780f8c7f4.jpg)

**Comment by thaytan** [comment]
Neat! I've never heard of it. I wonder how much of the CV1 work will translate

**Comment by Xanadu-Zen** [comment]
This manufacturer open source they frist genration product HR-MK1-HMD (pano in photos is HR-MK2-HMD), but  the MK1 is a laser positioning based devices, that might not help for MK2

**Comment by Xanadu-Zen** [comment]
My package is ready to go, please give me shipping address !

**Comment by thaytan** [comment]
I'm already going to be busy with Rift CV1 and Rift S quite a while - so if anyone else wants to work on this headset they should say so

**Comment by TheOnlyJoey** [comment]
@Xanadu-Zen please email me at info@thorworks.org will make sure we get a basic driver going, and hope that we can reuse part of the DK2/CV1 implementation!

**Comment by Xanadu-Zen** [comment]
@TheOnlyJoey 
I have sent the email yesterday，hoping for your reply!

**Comment by naratteu** [comment]
I also need an open source driver for hypereal pano.
I hope the link below will helpful.
https://github.com/hypereal-opensource

**Comment by shockla** [comment]
I just bought a used Hypereal Pano, Express on the way (a full set, seems to be same as picture above)
I heard that some chat group have offline driver installer (size: ~750MiB)
I'm trying to get it.

**Comment by kaibergman** [comment]
I have just received an MK2 headset in the mail without any lighthouses or controllers. Would anyone be able to send me the drivers?

**Comment by Xanadu-Zen** [comment]
> I have just received an MK2 headset in the mail without any lighthouses or controllers. Would anyone be able to send me the drivers?

**Comment by Xanadu-Zen** [comment]
> I have just received an MK2 headset in the mail without any lighthouses or controllers. Would anyone be able to send me the drivers?

I have upload the driver to Google drive, here is the link

**Comment by kaibergman** [comment]
Thank you, i'm downloading it now. Do you know of any way of getting some motion functionality without the official lighthouses ?

**Comment by kaibergman** [comment]
The Driver installed fine however now I can't get past the set up screen as it isn't detecting the HDMI. I believe it's because my hdmi output is connected to my igpu and not the dedicated graphics card. Is there no way past this? I suppose the hypereal software doesn't support my kind of hardware.

**Comment by Xanadu-Zen** [comment]
> Thank you, i'm downloading it now. Do you know of any way of getting some motion functionality without the official lighthouses ?

no，this hypereal driver can only support IR camera in headset kit 



> The Driver installed fine however now I can't get past the set up screen as it isn't detecting the HDMI. I believe it's because my hdmi output is connected to my igpu and not the dedicated graphics card. Is there no way past this? I suppose the hypereal software doesn't support my kind of hardware.

Driver need  find IR camera and controller connected to complete environment setup. The HDMI on headset should plug into dedicated AMD/Nvidia GPU this driver does not support Intel's iGPU
I don't know if there's a way to skip the environment setup, because I don't have this headset kit now.

**Comment by Holocala** [comment]
> Hypereal Pano is a multi camera IR blob tracking based VR headset, this headset start selling from June 2017, Include dual or triple camera, sens controller and the HMD. dual camera provide 240° and triple camera provide 360° tracking.
> The manufacturer also released compatible tools on Windows to work with SteamVR at that time. but after January 2018, the manufacturer was transformation to other industry and no longer to support this headset.
> With tons of updates from SteamVR, the compatible tools are not work with the latest SteamVR(can not detect the key press event in game ).
> Now this VR headset can only work perfectly with old version SteamVR (such as macos_beta, 1.3.23).
> Does anyone interested to support this devices? For necessary, I can giving a triple-Camera headset with the latest client drivers from manufacturer and old version SteamVR macos_beta for reverse engineering.

Hey bro can you give me steam vr 1.3.23 can’t find it everywhere.
