### ISSUE TITLE
API for VR-focused controllers

### ISSUE THREAD

**Issue by CandyAngel** [OpenHMD/OpenHMD#52]
OpenHMD currently does not expose an API for VR-focused controllers, such the Vive controllers or the P5 Glove (#51).

**Comment by TheOnlyJoey** [comment]
[device-class-and-flags branch in openhmd/openhmd](/openhmd/openhmd/tree/device-class-and-flags) has the basic framework for this and is supposed to be finished and merged soon.

**Comment by TheOnlyJoey** [comment]
Is tested and merged, does this follow the requirements set by this issue? @CandyAngel

**Comment by TheOnlyJoey** [comment]
As controllers have been tested for a while now (NOLO) this one can be closed.
