### ISSUE TITLE
CV1 Port ?

### ISSUE THREAD

**Issue by bouviervj** [OpenHMD/OpenHMD#60]
Project http://hg.sitedethib.com/libvr contains CV1 implementation, should be nice to have CV1 working with OpenHMD.

**Comment by TheOnlyJoey** [comment]
We already have CV1 support working since end of May on a branch https://github.com/OpenHMD/OpenHMD/tree/dev-oculus-cv1 will eventually be merged.

**Comment by bouviervj** [comment]
Cool thank you !
