### ISSUE TITLE
this maybe a cute bug.

### ISSUE THREAD

**Issue by dbx999** [OpenHMD/OpenHMD#62]
when i init my hmd,I see the code in function ohmd_create_oculus_rift_drv, this situation in the similar function(ohmd_create_external_drvm/ohmd_create_android_drv/ohmd_create_dummy_drv)
```
	drv->get_device_list = get_device_list;//1
	drv->open_device = open_device;//2
	drv->ctx = ctx;//3
	drv->get_device_list = get_device_list;//4
	drv->open_device = open_device;//5
	drv->destroy = destroy_driver;//6
```
1 and 4 are the same.2and 5 are same,I think these are not big bug,but why?

**Comment by noname22** [comment]
Well that's weird. Fixed, thanks for reporting.
