### ISSUE TITLE
-lthr missing on FreeBSD12

### ISSUE THREAD

**Issue by johalun** [OpenHMD/OpenHMD#69]
Hi

I need to do
export LDFLAGS='-lthr'
in order to link successfully. 

Please add this flag for FreeBSD.

**Comment by TheOnlyJoey** [comment]
I have to update my FreeBSD machine soon, so will check the compile then, thanks for the report!
Will update when checked/fixed.

**Comment by TheOnlyJoey** [comment]
CMake seems to work fine, i will add the flag to the autotools config and commit today.
Tested on TrueOS (FreeBSD 12)
