### ISSUE TITLE
Missing config.h file for building drv_htc_vive directory?

### ISSUE THREAD

**Issue by shinig4mi** [OpenHMD/OpenHMD#79]
Hi,

I have added options to cmake to build drv_htc_vive directory because I would like to read rotational data from the Vive.
I am on the htc-vive branch and getting the error below. I cannot locate the "config.h" file in the project.  Is this file and any others missing from the branch?
Thanks in advance for your help.

------------------
Changes to CMakeLists.txt
if(OPENHMD_DRIVER_VIVE)
	set(openhmd_source_files ${openhmd_source_files} 
	${CMAKE_CURRENT_LIST_DIR}/src/drv_htc_vive/vive.c
	${CMAKE_CURRENT_LIST_DIR}/src/drv_htc_vive/packet.c
	)
	add_definitions(-DDRIVER_VIVE)

	find_package(HIDAPI REQUIRED)
	include_directories(${HIDAPI_INCLUDE_DIRS})
	set(LIBS ${LIBS} ${HIDAPI_LIBRARIES})
endif(OPENHMD_DRIVER_VIVE)

Error:
C:\workplace\OpenHMD>make
Scanning dependencies of target openhmd
[  8%] Building C object CMakeFiles/openhmd.dir/src/drv_htc_vive/packet.c.obj
C:\workplace\OpenHMD\src\drv_htc_vive\packet.c:2:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make[2]: *** [CMakeFiles\openhmd.dir\build.make:238: CMakeFiles/openhmd.dir/src/drv_htc_vive/packet.c.obj] Error 1
make[1]: *** [CMakeFiles\Makefile2:67: CMakeFiles/openhmd.dir/all] Error 2
make: *** [Makefile:83: all] Error 2

**Comment by noname22** [comment]
I think @TheOnlyJoey has forgotten to add the files to the repo.

**Comment by shinig4mi** [comment]
Thanks @noname22 .
@TheOnlyJoey could you please add source files and a few instructions on compiling the htc-vive driver or using "simple" example for reading IMU data from Vive.
Cheers

**Comment by TheOnlyJoey** [comment]
Should be fixed, forgot to add the file, updated the CMake as well.
Both autotools and CMake both build the simple example by default, info is in the readme.
