### ISSUE TITLE
On htc-vive:  simple.exe cannot connect to HTC-VIVE

### ISSUE THREAD

**Issue by shinig4mi** [OpenHMD/OpenHMD#80]
Hi,

I would like to use the "simple" example provided to read IMU data from the HTC-VIVE.  
I've added the snippet below to the CMakeLists.txt in the package root to build the source in drv_htc_vive, however simple.exe does not connect to it.  It always connects to a "dummy device" regardless of what driver is built. Can you please provide some steps on how to connect to the htc-vive using the simple example?

Thanks

```
>simple.exe
num devices: 1
device 0
  vendor:  OpenHMD
  product: Dummy Device
  path:    (none)
```

OpenHMD/CMakeLists.txt code to build /src/drv_htc_vive
```
if(OPENHMD_DRIVER_VIVE)
	set(openhmd_source_files ${openhmd_source_files}
			${CMAKE_CURRENT_LIST_DIR}/src/drv_htc_vive/vive.c
			${CMAKE_CURRENT_LIST_DIR}/src/drv_htc_vive/packet.c
			)
	add_definitions(-DDRIVER_VIVE)
	find_package(HIDAPI REQUIRED)
	include_directories(${HIDAPI_INCLUDE_DIRS})
	set(LIBS ${LIBS} ${HIDAPI_LIBRARIES})
endif(OPENHMD_DRIVER_VIVE)
```

**Comment by TheOnlyJoey** [comment]
Sorry for the late response, but i have not been able to reproduce this.
Can you test with the 0.3rc branch please? should work out of the box.

**Comment by TheOnlyJoey** [comment]
This is also fixed in current master.
