### ISSUE TITLE
OS X Build not working (using DK2)

### ISSUE THREAD

**Issue by nebulusdesign** [OpenHMD/OpenHMD#84]
Working through the instructions in the README.md currently doesn't end up with a working build that the user can run the simple test app to see orientation quaternions from a connected DK2 device.

Out of the box following the instructions using either the autopen or cmake route to build, both fail.
The configure script doesn't find the hidapi library (I didn't dig further into this)
Using cmake it creates make files which include have -lrt which isn't available on OSX.

I tweaked the links.txt file that the makefile references and removed the -lrt, and both the library and simple app compile ok.

Upon trying to run simple it crashes with this reply:
```
num devices: 3

device 0
  vendor:  Oculus VR, Inc.
  product: Rift (DK2)
  path:    IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/Rift DK2@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14110000/Rift DK2@14110000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14110000,0

device 1
  vendor:  OpenHMD
  product: External Device
  path:    (none)

device 2
  vendor:  OpenHMD
  product: Dummy Device
  path:    (none)

Abort trap: 6
```

The path for the DK2 looked very suspicious so I tried the version of hidapi from brew rather than the GitHub one the instructions specify,  this produced a different path 

```
device 0
  vendor:  Oculus VR, Inc.
  product: Rift (DK2)
  path: USB_2833_0021_14110000
```

But with the same resulting `Abort trap: 6`

I think there is some issue with the way OpenHMD is using whatever hidapi is returning for the device, and it is unable to open the device correctly and crashing out.

**Comment by TheOnlyJoey** [comment]
So OVRService was running so it could not capture the usb device.
Might add a message reminding people to check for running services.
