### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by noname22** [OpenHMD/OpenHMD#9]

**Comment by rbalint** [comment]
I have created an official Debian package which can be ported to older Ubuntu versions:
https://tracker.debian.org/pkg/libopenhmd

**Comment by noname22** [comment]
Wow, that's awesome!

You mentioned something about needing XML for hardware detection. What is it you need us to do?

**Comment by noname22** [comment]
quoted from the e-mail, for the record:

As suggested by Paul Wise, Isenkram on Debian could recommend installing the libopenhmd package
when a supported device is attached to the computer.
Please help by shipping the needed xml files.

**Comment by noname22** [comment]
this link was also provided:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845272#10

**Comment by TheOnlyJoey** [comment]
Using backportpackage to maintain this Ubuntu PPA https://launchpad.net/~theonlyjoey/+archive/ubuntu/openhmd. Can be closed.
