### ISSUE TITLE
Feature request: Compatible drivers with TrueOpenVR standard

### ISSUE THREAD

**Issue by r57zone** [OpenHMD/OpenHMD#91]
[TrueOpenVR](https://github.com/TrueOpenVR) - is an very simple VR API and platform for users and developers.
Sample driver (dll library) - https://github.com/TrueOpenVR/TrueOpenVR-Drivers/blob/master/C%2B%2B/Sample/Sample/Sample.cpp
Docs - https://github.com/TrueOpenVR/TrueOpenVR-Core/blob/master/Library/README.md

**Comment by TheOnlyJoey** [comment]
So after checking the project Ii am not really sure what i am looking at, I see things written in pascal and delphi (which is quite deprecated) and I don't really see anything what we could contribute to.
OpenHMD is a standard by itself, if you want to implement it as a driver in your framework, feel free, but the project is not something that we would put effort in ourself.
